### PR TITLE
LPS-68088 Make sure the component is never assigned to itself

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
hey @sherlyliu, 

sorry for my late reply... this should be enough to fix the error you are seeing. I kept your changes in build.gradle, if those were introduced to fix this error please revert those as well as we should keep the dependencies to a minimum. 

Bests.

**Comment by sherlyliu** [comment]
Hi Carlos,

Thank you for you update, I checked it works fine.

Thanks,
Sherly

**Comment by csierra** [comment]
happy to hear! \o/

thanks to you!

**Comment by sherlyliu** [comment]
Hi Carlos,

Can you merge the changes to master branch?

Thanks,
Sherly

**Comment by csierra** [comment]
I can't myself... who is the maintainer? Greg? Do you want me to send the pull to him?

**Comment by sherlyliu** [comment]
Yes, you need send PR to him.

**Pull request closed without merging**
